### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by vvalvesga** [OpenReqEU/ri-collection-explicit-feedback-google-play-review#1]
Hi,

When I call this web service it returns me a lot of data, not a one review and I get a "runtime error: invalid memory address or nil pointer dereference"

It is correct?

Request:
`ip:9621/hitec/crawl/app-reviews/google-play/com.whatsapp/limit/1
`
Response:
```
.........................
.........................
<div class="single-review" tabindex="0">  <span> <span class="responsive-img-ldpi"> <span class="responsive-img author-image" style="background-image:url(https://lh5.googleusercontent.com/-0tCbEnp7xKM/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rcCMIfDnM1dzcuQ7Hv7W84FN0TPtQ/w48-h48-p/photo.jpg)"></span> </span> <span class="responsive-img-hdpi"> <span class="responsive-img author-image" style="background-image:url(https://lh5.googleusercontent.com/-0tCbEnp7xKM/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rcCMIfDnM1dzcuQ7Hv7W84FN0TPtQ/w96-h96-p/photo.jpg)"></span> </span> </span>  <div class="review-header" data-expand-target="" data-reviewid="gp:AOqpTOGvweSNIAfNNwjH2ujT3M1MHR_5KJk8VBUOFt9S6dKFm3NraR4KS8Y7Rjnqt9WYvYbQq5A_SOBVLo6GB44"> <div class="review-info"> <span class="author-name"> Ravikant Singh </span>  <span class="review-date">March 19, 2019</span> <a class="reviews-permalink" href="/store/apps/details?id=com.whatsapp&amp;reviewId=Z3A6QU9xcFRPR3Z3ZVNOSUFmTk53akgydWpUM00xTUhSXzVLSms4VkJVT0Z0OVM2ZEtGbTNOcmFSNEtTOFk3UmpucXQ5V1l2WWJRcTVBX1NPQlZMbzZHQjQ0" title=" Link to this review "></a> <div class="review-source" style="display:none"></div> <div class="review-info-star-rating">  <div class="tiny-star star-rating-non-editable-container" aria-label=" Rated 5 stars out of five stars "> <div class="current-rating" jsname="jIIjq" style="width: 100%;"></div> </div>  </div> </div> <div class="rate-review-wrapper"> <button class="play-button icon-button small rate-review" title=" Spam " data-rating="SPAM"> <div class="icon spam-flag"></div> </button> <button class="play-button icon-button small rate-review" title=" Helpful " data-rating="HELPFUL"> <div class="icon thumbs-up"></div> </button> <button class="play-button icon-button small rate-review" title=" Unhelpful " data-rating="UNHELPFUL"> <div class="icon thumbs-down"></div> </button> </div> </div> <div class="review-body with-review-wrapper"> <span class="review-title"></span> n <div class="review-link" style="display:none"> <a class="id-no-nav play-button tiny" href="#" target="_blank"> Full Review </a> </div> </div> </div> 
<div class="single-review" tabindex="0">  <span> <span class="responsive-img-ldpi"> <span class="responsive-img author-image" style="background-image:url(https://lh3.googleusercontent.com/-AuuJBCPWWT0/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rcB5bKxB57PiJZQabENtIY3nepfBw/w48-h48-p/photo.jpg)"></span> </span> <span class="responsive-img-hdpi"> <span class="responsive-img author-image" style="background-image:url(https://lh3.googleusercontent.com/-AuuJBCPWWT0/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rcB5bKxB57PiJZQabENtIY3nepfBw/w96-h96-p/photo.jpg)"></span> </span> </span>  <div class="review-header" data-expand-target="" data-reviewid="gp:AOqpTOELlsgmDmyjDREV-qDx5hp_lHO6So8NodVKabWGoorlH5V3l4k_mbrC8UEGJBVPdjT65ELe4Ot_q8MpwmU"> <div class="review-info"> <span class="author-name"> Rahul Sanap </span>  <span class="review-date">March 19, 2019</span> <a class="reviews-permalink" href="/store/apps/details?id=com.whatsapp&amp;reviewId=Z3A6QU9xcFRPRUxsc2dtRG15akRSRVYtcUR4NWhwX2xITzZTbzhOb2RWS2FiV0dvb3JsSDVWM2w0a19tYnJDOFVFR0pCVlBkalQ2NUVMZTRPdF9xOE1wd21V" title=" Link to this review "></a> <div class="review-source" style="display:none"></div> <div class="review-info-star-rating">  <div class="tiny-star star-rating-non-editable-container" aria-label=" Rated 5 stars out of five stars "> <div class="current-rating" jsname="jIIjq" style="width: 100%;"></div> </div>  </div> </div> <div class="rate-review-wrapper"> <button class="play-button icon-button small rate-review" title=" Spam " data-rating="SPAM"> <div class="icon spam-flag"></div> </button> <button class="play-button icon-button small rate-review" title=" Helpful " data-rating="HELPFUL"> <div class="icon thumbs-up"></div> </button> <button class="play-button icon-button small rate-review" title=" Unhelpful " data-rating="UNHELPFUL"> <div class="icon thumbs-down"></div> </button> </div> </div> <div class="review-body with-review-wrapper"> <span class="review-title"></span> mast <div class="review-link" style="display:none"> <a class="id-no-nav play-button tiny" href="#" target="_blank"> Full Review </a> </div> </div> </div> ",1]

get the helpfulnes score
2019/03/18 14:51:12 http: panic serving ip:49661: runtime error: invalid memory address or nil pointer dereference
goroutine 73 [running]:
net/http.(*conn).serve.func1(0xc420334640)
        /usr/local/go/src/net/http/server.go:1697 +0xd0
panic(0x6b27a0, 0x89ad10)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/anaskhan96/soup.Root.Text(0x0, 0x0, 0x0, 0x86cd60, 0xc42021fab0, 0xc420049748, 0x3)
        /go/src/github.com/anaskhan96/soup/soup.go:267 +0x26
main.getHelpfulness(0xc4204ba620, 0x71ce2b, 0x3, 0x0, 0x0, 0x5)
        /go/src/app/crawler.go:176 +0x166
main.Crawl(0xc42024e079, 0xc, 0x1, 0x0, 0x0, 0x0)
        /go/src/app/crawler.go:96 +0x10dc
main.getAppReviews(0x871160, 0xc420158000, 0xc42012c400)
        /go/src/app/starter.go:35 +0x14b
net/http.HandlerFunc.ServeHTTP(0x720b48, 0x871160, 0xc420158000, 0xc42012c400)
        /usr/local/go/src/net/http/server.go:1918 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc42010e000, 0x871160, 0xc420158000, 0xc42012c200)
        /go/src/github.com/gorilla/mux/mux.go:212 +0xcd
net/http.serverHandler.ServeHTTP(0xc420074d00, 0x871160, 0xc420158000, 0xc42012c200)
        /usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc420334640, 0x8716a0, 0xc4202dc240)
        /usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2720 +0x288

```

**Comment by ChristophStanik** [comment]
Hi,
as stated in the readme file, we cannot maintain the google play crawlers as the HTML we are crawling is continuously updated and that data is currently not used within the project. We may update it in the future, but I cannot promise anything.

**Comment by jnerlich** [comment]
@vvalvesga is your issue solved with  @ChristophStanik answer?

**Comment by jnerlich** [comment]
@ChristophStanik Was the documentation improved? Can we close this issue?

**Comment by vvalvesga** [comment]
@jnerlich For me, this issue can be closed. Although it would be nice to have that section

**Comment by jnerlich** [comment]
@ChristophStanik could you please improve the documentation?

**Comment by ChristophStanik** [comment]
@jnerlich I updated the readme with further information.
